### ISSUE TITLE
feature request: refactoring :)

### ISSUE THREAD

**Issue by ruscon** [nanogiants/nestjs-swagger-api-exception-decorator#1]
Hi, good idea about decorator

But, read please about nestjs v7: https://docs.nestjs.com/migration-guide#http-exceptions-body

### HTTP exceptions body
Previously, the generated response bodies for the HttpException class and other exceptions derived from it (e.g., BadRequestException or NotFoundException) were inconsistent. In the latest major release, these exception responses will follow the same structure.

```javascript
/*
 * Sample outputs for "throw new ForbiddenException('Forbidden resource')"
 */

// Before
{
  "statusCode": 403,
  "message": "Forbidden resource"
}

// After
{
  "statusCode": 403,
  "message": "Forbidden resource",
  "error": "Forbidden"
}
```

And about refactoring, we can
1. `exception` should be an arrow function (example https://github.com/typestack/class-transformer#working-with-nested-objects)
2. add an optional `schema` prop because a `message` can have a custom type
3. add `error` prop and it is optional as I see in the nestjs code

```typescript
import type { HttpException, Type } from '@nestjs/common';
import type { ApiResponseOptions } from '@nestjs/swagger';
import { ApiResponse, getSchemaPath } from '@nestjs/swagger';
import { getTypeIsArrayTuple } from '@nestjs/swagger/dist/decorators/helpers';
import type { ResponseObject, SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';

export type Func = () => void;

export interface ApiExceptionOptions extends Omit<ResponseObject, 'description'> {
    description?: string;
    type?: Func | [Func];
    isArray?: boolean;
    schema?: SchemaObject;
}

export const ApiException = <T extends HttpException>(exception: () => Type<T>, options: ApiExceptionOptions = {}): MethodDecorator & ClassDecorator => {
    const instance = new (exception())();

    const apiResponseOptions: ApiResponseOptions = {
        status: instance.getStatus(),
        description: options?.description || instance.message,
        schema: {
            type: 'object',
            properties: {
                statusCode: {
                    type: 'number',
                    example: instance.getStatus(),
                },
                message: {
                    type: 'string',
                },
                error: {
                    type: 'string',
                    example: instance.message,
                },
            },
            required: ['statusCode', 'message'],
        },
    };

    if (!apiResponseOptions.schema.properties) {
        throw new TypeError('"apiResponseOptions.schema.properties" is undefined');
    }

    if (options.schema) {
        apiResponseOptions.schema.properties.message = options.schema;
    } else if (options.type) {
        const [type, isArray] = getTypeIsArrayTuple(options.type, !!options.isArray);
        if (!type) {
            throw new TypeError('"type" is undefined');
        }
        apiResponseOptions.schema.properties.message['$ref'] = getSchemaPath(type());

        if (isArray) {
            apiResponseOptions.schema.properties.message = {
                type: 'array',
                items: {
                    type: 'object',
                    $ref: apiResponseOptions.schema.properties.message['$ref'],
                },
            };
        }
    }

    return ApiResponse(apiResponseOptions);
};
```

examples after refactoring

```typescript
@ApiException(() => NotFoundException)
@ApiException(() => NotFoundException, { description: 'Custom description' })
@ApiException(() => NotFoundException, { description: 'Custom description', schema: { /** custom schema for message prop */} }
@ApiException(() => NotFoundException, { description: 'Custom description', type: () => SomeClassWithSwaggerAnnotitions, isArray: true }
```

screenshot: https://monosnap.com/file/17EcP6XlkJN7dwaJ3JyRBK9YQvQN1t

P.S. If you think about it, you can probably do even better :)

**Comment by ruscon** [comment]
btw @kamilmysliwiec this is a good idea for the @nestjs/swagger itself :)

**Comment by jsproede** [comment]
Hey, 

thank you very much for your refactoring suggestions. We've never used nestjs/swagger at this level but it's great to get some more insights 👍 

As you already created an issue in the nestjs/swagger repository, I'd suggest we wait and see if this decorator will be implemented directly inside NestJS swagger module, where I think this decorator belongs.

**Comment by jsproede** [comment]
Hi @ruscon, I'm going to address your refactoring suggestions soon, as we now have the answer, that this feature is not going to be implemented directly in NestJS swagger module.

**Comment by ruscon** [comment]
@jsproede yep, I saw, thx

**Comment by ruscon** [comment]
One sec, I will update the code

**Comment by ruscon** [comment]
done

**Comment by jsproede** [comment]
Hi @ruscon. We've released a new version which contains your suggestions: [Release Notes](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/releasenotes/v1.2.0)

Thank you very much for opening this issue. It helped us a lot to get more insights how NestJS Swagger works internally :)
