### ISSUE TITLE
Grouping under the wrong status code

### ISSUE THREAD

**Issue by lzkill** [nanogiants/nestjs-swagger-api-exception-decorator#13]
I have two custom exceptions as described in the [docs](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/gettingstarted/usage/templated).

**unauthorized-exceptions.ts**
``` typescript
import { UnauthorizedException } from '@nestjs/common';

export class UserNotAuthorizedException extends UnauthorizedException {
  constructor() {
    super('The user is not authorized');
  }
}
```

**bad-request-exceptions.ts**
```typescript
import { BadRequestException, ValidationError } from '@nestjs/common';

export class ValidationFailedException extends BadRequestException {
  private _validationErrors: ValidationError[];
  constructor(validationErrors: ValidationError[]) {
    super('Validation failed');
    this._validationErrors = validationErrors;
  }

  get validationErrors() {
    return this._validationErrors;
  }
}
```
When I declare them using an array the Swagger doc puts both under 400 code. I get 400 and 401 examples only if I declare them using two  `@TemplatedApiException`.

**This produces wrong grouping:**
```typescript
  @ApiResponse({
    status: 201,
    type: UserDto,
  })
  @TemplatedApiException([
    ValidationFailedException,
    UserNotAuthorizedException,
  ])
  @Post()
  create(@Body() user: CreateUserDto): Promise<UserDto> {
    return this.userService.create(user);
  }
```

**This produces right groping (400 and 401):**

```typescript
  @ApiResponse({
    status: 201,
    type: UserDto,
  })
  @TemplatedApiException(ValidationFailedException)
  @TemplatedApiException(UserNotAuthorizedException)
  @Post()
  create(@Body() user: CreateUserDto): Promise<UserDto> {
    return this.userService.create(user);
  }
```

**Comment by jsproede** [comment]
Hi @lzkill, thanks for reporting the issue. 

Initially we wanted to keep the same structure as the NestJS Swagger built-in decorators, as you would've to use multiple decorators to define multiple exceptions with different status codes. [Thus the decorator prints a warning to the console](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/gettingstarted/usage/custom#pass-exceptions-as-an-array), if the exceptions passed with one decorator call contain different status codes. 

But as this decorator shows exceptions in a different way, it would make sense, that all exceptions for one route could be passed as single array without the use of multiple decorators attached to one method. Another issue is, that the warning when starting the NestJS backend is printed too early and is not visible long enough.

We'll take a look at this soon and fix this issue if one array contains exceptions with multiple status codes :)

**Comment by jsproede** [comment]
Hi @lzkill. We've released a new version which now groups exceptions properly if exceptions with different status codes are passed to a single decorator call :)

[Release Notes v1.2.0](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/releasenotes/v1.2.0)

**Comment by lzkill** [comment]
Thank you very much!
