### ISSUE TITLE
type attribute doesn't work with custom exceptions

### ISSUE THREAD

**Issue by lzkill** [nanogiants/nestjs-swagger-api-exception-decorator#16]
I have a Swagger annotated class:

```typescript
import { ApiProperty } from '@nestjs/swagger';

export class BaseExceptionTemplate {
  @ApiProperty({required: true,type: Number})
  statusCode: number;

  @ApiProperty({required: false, type: Number})
  clientCode: string;

  @ApiProperty({required: true, type: String})
  message: string;

  @ApiProperty({required: false, type: [String]})
  errors: string[];

  @ApiProperty({required: false,type: String})
  path: string;

  @ApiProperty({required: false,type: String,})
  timestamp: string;
}
```

My controller method is the following:

```typescript
  @Post('/register')
  @ApiOperation({ summary: 'Registra um novo usuário' })
  @ApiResponse({
    status: 201,
    description:
      'Usuário registrado com sucesso. Um e-mail com instruções será enviado para o endereço cadastrado.',
  })
  @ApiException(() => ClienteNaoEncontradoException, {type: () => BaseExceptionTemplate})
  @ApiException(() => ClienteJaCadastradoException, {type: () => BaseExceptionTemplate})
  @ApiException(() => LigacaoNaoEncontradaException, {type: () => BaseExceptionTemplate})
  @ApiException(() => EmailJaCadastradoException, {type: () => BaseExceptionTemplate})
  @ApiException(() => ValidationFailedException, {type: () => BaseExceptionTemplate})
  register(@Body() registerDto: RegisterDto) {
    throw new NotImplementedException('Not yet implemented!');
  }
```
The final Swagger example contains only this:

```
{
  "statusCode": 409,
  "message": "E-mail já cadastrado",
  "error": "E-mail já cadastrado"
}
```
Shouldn't it resemble the annotated class?

**Comment by jsproede** [comment]
Hi @lzkill, thank you for reporting the issue.
The `type` is indeed missing in the Swagger example value. We'll take a look at this issue soon :)

I have a question regarding the usage of `type` here: Do you want to override the whole template with `BaseExceptionTemplate` which will be shown in Swagger UI or just the `message` property?
In the current implementation of the decorator, the `type` is attached to the `message` property:
![decorator-example-schema](https://user-images.githubusercontent.com/13382203/115511457-24fd6800-a281-11eb-8e0c-fc2756aa0e35.png)
The example value then contains the `statusCode` twice. Is this intended by you? :)

**Comment by lzkill** [comment]
Hi @jsproede. How are you? Yes, I was trying to override the whole template. This would be a clean way to define the structure to show on the GUI. What are you thoughts on this?

**Comment by jsproede** [comment]
@lzkill You're right. We'll take a look at this, because currently the `type` is attached to `message` it would be a breaking change if we'd release a new version which uses the `type` as main example/schema value :)

**Comment by lzkill** [comment]
I think this would be awesome! That definitely fills the gap with the whole @ApiException thing.

**Comment by jsproede** [comment]
Hi @lzkill. The issue with missing example response values specified with `type` property has been fixed and will be available in the next version :) I've moved the usage of Swagger annotated classes together with the `template` property into a new issue.
