### ISSUE TITLE
How to document optional attributes with buildTemplatedApiExceptionDecorator?

### ISSUE THREAD

**Issue by lzkill** [nanogiants/nestjs-swagger-api-exception-decorator#17]
I have this template decorator:

```typescript
import { buildTemplatedApiExceptionDecorator } from '@nanogiants/nestjs-swagger-api-exception-decorator';

export const TemplatedApiException = buildTemplatedApiExceptionDecorator({
  statusCode: '$status',
  clientCode: 'number',
  message: '$description',
  errors: [
    {
      string: 'string',
    },
  ],
  path: 'string',
  timestamp: '1970-01-01T15:30:11',
});
```

It matches my exception filter custom json. But some attributes are optional. Hoe can I document this on Swagger?

**Comment by jsproede** [comment]
Hi @lzkill, with the `@TemplatedApiException` decorator currently it is not possible to mark attributes as optional. 

What do you think about an optional array which can contain the required attributes? For example:
```typescript
export const TemplatedApiException = buildTemplatedApiExceptionDecorator({
  statusCode: '$status',
  clientCode: 'number',
  message: '$description',
  errors: [
    {
      string: 'string',
    },
  ],
  path: 'string',
  timestamp: '1970-01-01T15:30:11',
}, ['statusCode', 'message', 'timestamp']);
```

**Comment by lzkill** [comment]
Hi my friend. I guess this array would pretty much fit my needs. Without this the api consumer is not aware until the first errors start to return.

**Comment by jsproede** [comment]
Hi @lzkill,

we've extended the `Options` interface with `requiredProperties`. For example:
```typescript
export const TemplatedApiException = buildTemplatedApiExceptionDecorator(
  {
    statusCode: '$status',
    clientCode: 'number',
    message: '$description',
    errors: [
      {
        string: 'string',
      },
    ],
    path: 'string',
    timestamp: '1970-01-01T15:30:11',
  },
  { requiredProperties: ['statusCode', 'message', 'timestamp'] },
);
```

We'll release a new version (v1.3.0) soon :)

**Comment by lzkill** [comment]
Thank you again, my friend!

**Comment by lzkill** [comment]
@jsproede What do you think about having a similar array for custom placeholders?

**Comment by jsproede** [comment]
@lzkill Do you have an example? :)

**Comment by lzkill** [comment]
Something like this:

```typescript
export const TemplatedApiException = buildTemplatedApiExceptionDecorator(
  {
    statusCode: '$status',
    clientCode: '$clientCode',
    message: '$description',
    errors: [
      {
        string: 'string',
      },
    ],
    path: 'string',
    timestamp: '1970-01-01T15:30:11',
  },
  {
    requiredProperties: ['statusCode', 'message', 'timestamp'],
    placeholders: {
       'clientCode': (e) => { (e as BaseException).getClientCode(); }
    }
  },
);
```

(I'm sorry for my poor typescript)

**Comment by jsproede** [comment]
@lzkill Great idea! I've moved your suggestion regarding custom placeholders into a new issue :)

**Comment by jsproede** [comment]
Hi @lzkill, I just wanted to notify you, that a new version including the `requiredProperties` property has been released :) The new release also includes custom placeholders. We described the new properties in our [documentation](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/api/#requiredproperties).

**Comment by lzkill** [comment]
Hi my friend. I was already using your first commit. :)

Thank you very much for your superb work!
