### ISSUE TITLE
Wrong tslint depricated warning

### ISSUE THREAD

**Issue by rostamiani** [nanogiants/nestjs-swagger-api-exception-decorator#25]
I believe there is a wrong deprication warning here.
This is my code:
```ts
  @ApiOkResponse({ type: RegisterByEmailResponseDto })
  @ApiException(() => UserAlreadyExistsException)
  @ApiException(() => InternalServerException)
  async register(
    @Body() registerInfo: RegisterDto,
   ...
```

And this is the warnning:
```
Deprecated: This decorator signature will be removed in future versions. Please provide HttpExceptions as function:

\@ApiException(() => BadRequestException, [options])eslintimport/no-deprecated
```

**Comment by jsproede** [comment]
Hi @rostamiani, thank you for opening this issue. I believe this could be a problem with TSLint having issues detecting the deprecated overloaded decorator signature properly. As TSLint is deprecated and a migration to ESLint is advised: Is it possible for you to migrate your NestJS backend to ESLint? 
We orientated at [this comment](https://github.com/nestjs/typescript-starter/issues/69#issuecomment-592457660) and had no issues migrating to ESLint in our NestJS project.
