### ISSUE TITLE
Cannot add multilpe exception with similar status codes

### ISSUE THREAD

**Issue by rostamiani** [nanogiants/nestjs-swagger-api-exception-decorator#26]
Hi
When I add multiple custom exceptions that have similar statuscodes, only the first one is displayed. Is it possible to handle this with `oneOf` swagger property?

For example this is my code:
```ts
  @ApiException(() => [
    UserAlreadyExistsException,
    InternalServerException,
    EmailResponseFailedEexception,
  ])
```
Two last exceptions have different error messages but both have status 500.
This is the output:
![image](https://user-images.githubusercontent.com/1157108/116806795-915f4d80-ab44-11eb-8afc-eef5b7a2828b.png)

**Comment by jsproede** [comment]
Hi @rostamiani, thank you for opening this issue. Just to understand you correctly:
The `InternalServerException` and `EmailResponseFailedEexception` both have the status code `500`. Then this decorator attaches them as `example` in Swagger UI. Is the `EmailResponseFailedEexception` missing in the `Examples` dropdown at status code `500`?

**Comment by rostamiani** [comment]
> Hi @rostamiani, thank you for opening this issue. Just to understand you correctly:
> The `InternalServerException` and `EmailResponseFailedEexception` both have the status code `500`. Then this decorator attaches them as `example` in Swagger UI. Is the `EmailResponseFailedEexception` missing in the `Examples` dropdown at status code `500`?

Exacty... :rose:

**Comment by jsproede** [comment]
Which version of the decorator you're using? :)
I just wrote a test and extended our demo project, which contains two exceptions sharing the same status code and the payload is build correctly:
![same status code](https://user-images.githubusercontent.com/13382203/116848071-1baebc80-abec-11eb-86c0-4700d54f9ea2.png)

If you're using the latest version (v.1.4.1): Could you share how your custom exceptions look like? :)

**Comment by rostamiani** [comment]
I just didn't see that...
Both errors are already there :+1:

**Comment by jsproede** [comment]
Great :) I'll close this issue then
