### ISSUE TITLE
Wrong exception body when exception body is an object

### ISSUE THREAD

**Issue by rostamiani** [nanogiants/nestjs-swagger-api-exception-decorator#27]
The generated exception body is duplicated with my custom exception

This is my custom exception:
```ts
export class CodeInvalidException extends UnauthorizedException {
  constructor(error?: string) {
    super(
      {
        code: ExcepionsEnum.CODE_INVALID,
        message: 'Your provided code is invalid, please try again',
      },
      error,
    );
  }
}
```
And this is the Swagger output:
```json
{
  "statusCode": 401,
  "message": "Your provided code is invalid, please try again",
  "error": "Your provided code is invalid, please try again"
}```

And this is the expected output:
```json
{
  "statusCode": 401,
  "message": "Your provided code is invalid, please try again",
  "error": "string"
}
```

**Comment by rostamiani** [comment]
Now I found the templating feature and it's perfect! But I have struggling to add code placeholder.

This is m template:
```ts
export const ApiCustomException = buildTemplatedApiExceptionDecorator(
  {
    code: '$code',
    message: '$description',
  },
  {
    placeholders: buildPlaceholder(
      () => InternalServerException,
      exception => ???,
    ),
  },
);
```
And I don't know if it's possible to get my custom error code from exception object. This is one of my exception objects as mentioned in the first post:
```ts
export class CodeInvalidException extends UnauthorizedException {
  constructor(error?: string) {
    super(
      {
        code: ExcepionsEnum.CODE_INVALID,
        message: 'Your provided code is invalid, please try again',
      },
      error,
    );
  }
}
```

**Comment by jsproede** [comment]
Hi :)

If you pass the error as second argument, you're [overriding the description](https://github.com/nestjs/nest/blob/master/packages/common/exceptions/unauthorized.exception.ts#L38) of the `UnauthorizedException` which is `Unauthorized`. Is this intended by you?

I'd assume, that the error needs to be in the first object:
```typescript
export class CodeInvalidException extends UnauthorizedException {
  constructor(error?: string) {
    super({
      code: '1000',
      message: 'Your provided code is invalid, please try again',
      error,
    });
  }
}
```

The default behavior then by the `@ApiException` decorator is, that if `error` is undefined, it takes the `message` by the exception. To override the `error` with a `string` value, you could then do the following:
```typescript
@ApiException(() => new CodeInvalidException('string'))
```
This overwrites the `error` property with the given string.

**Comment by jsproede** [comment]
I'm closing this issue for now. Feel free to open this issue again if you have any further questions :)
