### ISSUE TITLE
Description not used as Example Value message

### ISSUE THREAD

**Issue by f3l1x98** [nanogiants/nestjs-swagger-api-exception-decorator#40]
According to the API spec [here](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/api), the description of the options should be used as the message in the Example Value, but it isn't.
For example in the demo project:
https://github.com/nanogiants/nestjs-swagger-api-exception-decorator/blob/d2dcb1da450617f424152526b17f3674cb475ccf/demo/src/app.controller.ts#L148-L157
should generate an example value like this:
```
{
    "statusCode": 400,
    "message": "Required attributes were missing",
    "error": "Bad Request"
}
```
but it generates this:
```
{
    "statusCode": 400,
    "message": "Bad Request",
    "error": "Bad Request"
}
```
![ExceptionApiSwagger](https://user-images.githubusercontent.com/52160939/168540019-390af243-25e9-42aa-97ad-504580f3d5a2.png)

**Comment by dasheck0** [comment]
You have to use templated exceptions for this. Refer to section [https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/gettingstarted/usage/templated](https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/gettingstarted/usage/templated) and the following code:

```
import {
  BadRequestException,
  Controller,
  Get,
} from '@nestjs/common';
import { AppService } from './app.service';

import { ApiException } from '@nanogiants/nestjs-swagger-api-exception-decorator';
import { ApiOperation } from '@nestjs/swagger';
import { HttpException } from '@nestjs/common';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @ApiOperation({ summary: 'Changes the users password' })
  @ApiException<HttpException>(() => BadRequestException, {
    template: {
      message: 'Required attributes were missing',
    }
  })
  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}
```

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/4851711/169704647-e161e06b-134c-4f49-a0eb-84f1c39cf3a1.png">

Please reopen ticket if the issue still persists. Thanks!

**Comment by f3l1x98** [comment]
I am sorry, my initial issue description was not clear enough:
**The issue is that the `$description` is not working.**

According to the documentation linked in the issue the following code 
```
import {
  BadRequestException,
  Controller,
  Get,
} from '@nestjs/common';
import { AppService } from './app.service';

import { ApiException } from '@nanogiants/nestjs-swagger-api-exception-decorator';
import { ApiOperation } from '@nestjs/swagger';
import { HttpException } from '@nestjs/common';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @ApiOperation({ summary: 'Changes the users password' })
  @ApiException<HttpException>(() => BadRequestException, {
    description: 'Required attributes were missing',
    template: {
      message: '$description',
    }
  })
  @Get()
  getHello(): string {
    return this.appService.getHello();
  }
}
```
should result into the same example value as your's:
```
{
    "message": "Required attributes were missing",
}
```
But it results into
![image](https://user-images.githubusercontent.com/52160939/170205182-b907961f-6d67-425a-9066-09795cc3a4eb.png)

Or did I missunderstood this part (Maybe I am thinking of the wrong Options?)
![image](https://user-images.githubusercontent.com/52160939/170205413-fbf5ff3a-e177-456f-bd26-bd162bc284d8.png)

**Comment by dasheck0** [comment]
You can use the template property to set example values in your swagger documentation. We parse the type of exception and therefore know what status code, description and error should be displayed as example value. But we wanted to provide a way to override them as well. Basically you have three things you can do and I will illustrate that with the `message` property. But this will work for `statusCode` and `error` property as well:

**1. Omit message property**
```
{
  template: {
  }
}
```
No example value for message will be displayed

**2. Add message property with custom string**
```
{
  template: {
    message: "Custom string"
  }
}
```
Example value for message will be "Custom string"


**3. Add message property with value $description**
```
{
  template: {
    message: "$description"
  }
}
```
Example value for message will be the default message of the passed exception.

So in your case if you want to specify a custom message, use option 2 and set a custom string to template.message. The `description` you set in the Options property is only used for the description of the example (not the example itself). See screenshot below. In this case I chose option 3 and provided the default message of the passed exception, which is an `UnauthorizedException`

 ![github2](https://user-images.githubusercontent.com/4851711/170681076-d39bccfd-cfa3-4af4-a086-243cab1df8e5.png)

Hope this helps. If so I will updated the documentation accordingly.

**Comment by f3l1x98** [comment]
Now I understand, thank you very much.
Looks like I did misunderstand the documentation.
