### ISSUE TITLE
Update peer dependencies for new Nest versions

### ISSUE THREAD

**Issue by kasvith** [nanogiants/nestjs-swagger-api-exception-decorator#42]
Current peer deps are outdated

**Comment by dasheck0** [comment]
Thanks for the issue. Will deal with this and update soon.

**Comment by kasvith** [comment]
@dasheck0 I tried with `npm i --force`  with the latest nest. it worked fine

**Comment by dasheck0** [comment]
Fixed with https://github.com/nanogiants/nestjs-swagger-api-exception-decorator/commit/fda03a1d0561a7b3c3a15ab95e42fdca9da3d146. Should be available on npm soon (after the action ran through)

**Comment by kasvith** [comment]
isnt this ready yet :/
