### ISSUE TITLE
Create new GH release for version 1.6.3

### ISSUE THREAD

**Issue by bmxpiku** [nanogiants/nestjs-swagger-api-exception-decorator#44]
Since with version 1.6.3 there is support to nestjs 9+ 
I think its relevant to add github release with it - since I found out there is a new version by checking releases on npm - when also trying to figure out issues with running version 1.6 with nest 9.

Maybe also adding info here https://nanogiants.github.io/nestjs-swagger-api-exception-decorator/releasenotes/v1.6.0
that version > 1.6.0 is required for latest nest?

**Comment by dasheck0** [comment]
Sorry for the delay. The release is now available at https://github.com/nanogiants/nestjs-swagger-api-exception-decorator/releases/tag/v1.6.3
