### ISSUE TITLE
Outdated NestJS version

### ISSUE THREAD

**Issue by johnkrzywanek** [nanogiants/nestjs-swagger-api-exception-decorator#53]
Hello, looks like there are some conflicts while updating NestJS installations that are using this package due to outdated `@nestjs/common` dependency in this package. Could you please bump those dependencies?

**Comment by dasheck0** [comment]
Thanks for pointing this out. See latest version 1.6.10:

- https://github.com/nanogiants/nestjs-swagger-api-exception-decorator/releases/tag/v1.6.10
- https://www.npmjs.com/package/@nanogiants/nestjs-swagger-api-exception-decorator
